### ISSUE TITLE
Got the error about TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by chathawee** [thoughtspot/cs_tools#107]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my designated Account Executive and Solutions Consultant team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Platform Configuration

Python 3.8
CentOS 7

### Description

I already installed the cs_tools on the CentOS7 but I faced the error about TypeError: 'type' object is not subscriptable. However, before I install the CS tools, I have upgraded the python from python3.6.8 to version 3.8.0. After I done upgrade the python. I have run this command `curl --silent --show-error --location-trusted https://raw.githubusercontent.com/thoughtspot/cs_tools/master/cs_tools/updater/_bootstrapper.py | python3 - --install` After done restarting the terminal. I started the command with `cs_tools version` but I got the error below
Traceback (most recent call last):
  File "/root/.config/cs_tools/.cs_tools/bin/cs_tools", line 8, in <module>
    sys.exit(run())
  File "/root/.config/cs_tools/.cs_tools/lib/python3.8/site-packages/cs_tools/cli/main.py", line 136, in run
    _setup_tools(_tools.app, ctx_settings=app.info.context_settings)
  File "/root/.config/cs_tools/.cs_tools/lib/python3.8/site-packages/cs_tools/cli/main.py", line 94, in _setup_tools
    tool = get_cs_tool(path.name)
  File "/root/.config/cs_tools/.cs_tools/lib/python3.8/site-packages/cs_tools/programmatic.py", line 21, in get_cs_tool
    return CSTool(tool_dir)
  File "pydantic/dataclasses.py", line 348, in pydantic.dataclasses._add_pydantic_validation_attributes.new_init
  File "/root/.config/cs_tools/.cs_tools/lib/python3.8/site-packages/cs_tools/cli/loader.py", line 47, in __post_init_post_parse__
    self.app.rich_help_panel = "Available Tools"
  File "/root/.config/cs_tools/.cs_tools/lib/python3.8/site-packages/cs_tools/cli/loader.py", line 117, in app
    return self.lib.app
  File "/root/.config/cs_tools/.cs_tools/lib/python3.8/site-packages/cs_tools/cli/loader.py", line 108, in lib
    self._lib = importlib.import_module(import_path)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.config/cs_tools/.cs_tools/lib/python3.8/site-packages/cs_tools/cli/tools/git/__init__.py", line 2, in <module>
    from .app import app
  File "/root/.config/cs_tools/.cs_tools/lib/python3.8/site-packages/cs_tools/cli/tools/git/app.py", line 12, in <module>
    from .config import app as configApp
  File "/root/.config/cs_tools/.cs_tools/lib/python3.8/site-packages/cs_tools/cli/tools/git/config.py", line 176, in <module>
    def _show_configs_as_table(configs: list[dict], title: str = "Configuration Details"):
TypeError: 'type' object is not subscriptable

Could anyone help fix this?

Thanks,
May

**Comment by boonhapus** [comment]
Hi @chathawee ! Can you try using the `--reinstall` option instead? The internal virtual environment is likely symlinked to the older python version. The `--reinstall` option should delete the old venv and create a new one.

```bash
curl --silent --show-error --location-trusted https://raw.githubusercontent.com/thoughtspot/cs_tools/master/cs_tools/updater/_bootstrapper.py | python3 - --reinstall
```

**Comment by chathawee** [comment]
It's passed now and I can run it. Thanks @boonhapus
