### ISSUE TITLE
error on cs_tools config creation [zlib.error: Error -3 while decompressing data: incorrect header check] 

### ISSUE THREAD

**Issue by felipemm** [thoughtspot/cs_tools#124]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my designated Account Executive and Solutions Consultant team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Platform Configuration

│                                                                                                                      │
│           Info snapshot taken on 2024-04-12                                                                          │
│                                                                                                                      │
│               CS Tools: 1.5.1                                                                                        │
│         Python Version: Python 3.10.8 (main, Dec  8 2022, 10:52:18) [Clang 14.0.0 (clang-1400.0.29.202)]             │
│            System Info: Darwin (detail: macOS-12.7.1-x86_64-i386-64bit)                                              │
│      Configs Directory: /Users/ {anonymous} /Library/Application Support/cs_tools                                    │
│    Activate VirtualEnv: source "/Users/ {anonymous} /Library/Application Support/cs_tools/.cs_tools/bin/activate"    │
│          Platform Tags: macosx-12.6-x86_64                                                                           │
│                                                                                                                     

### Description

cs_tools config create --config test --url test.thoughtspot.cloud --username teste@test.com --password test123 --verbose

gives the following error:

```[DEBUG - 2024-04-12T15:26:03-0300] [cs_tools.cli.commands.main - main.run 126] whoopsie, something went wrong!
Traceback (most recent call last):
  File "/Users/felipe.matos/Library/Application Support/cs_tools/.cs_tools/lib/python3.10/site-packages/cs_tools/cli/commands/main.py", line 101, in run
    return_code = app(standalone_mode=False)
  File "/Users/felipe.matos/Library/Application Support/cs_tools/.cs_tools/lib/python3.10/site-packages/typer/main.py", line 326, in __call__
    raise e
  File "/Users/felipe.matos/Library/Application Support/cs_tools/.cs_tools/lib/python3.10/site-packages/typer/main.py", line 309, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Users/felipe.matos/Library/Application Support/cs_tools/.cs_tools/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/felipe.matos/Library/Application Support/cs_tools/.cs_tools/lib/python3.10/site-packages/typer/core.py", line 723, in main
    return _main(
  File "/Users/felipe.matos/Library/Application Support/cs_tools/.cs_tools/lib/python3.10/site-packages/typer/core.py", line 193, in _main
    rv = self.invoke(ctx)
  File "/Users/felipe.matos/Library/Application Support/cs_tools/.cs_tools/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/felipe.matos/Library/Application Support/cs_tools/.cs_tools/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/felipe.matos/Library/Application Support/cs_tools/.cs_tools/lib/python3.10/site-packages/cs_tools/cli/ux.py", line 38, in invoke
    r = ctx.invoke(self.callback, **ctx.params)
  File "/Users/felipe.matos/Library/Application Support/cs_tools/.cs_tools/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/felipe.matos/Library/Application Support/cs_tools/.cs_tools/lib/python3.10/site-packages/typer/main.py", line 692, in wrapper
    return callback(**use_params)
  File "/Users/felipe.matos/Library/Application Support/cs_tools/.cs_tools/lib/python3.10/site-packages/cs_tools/cli/commands/config.py", line 86, in create
    conf = CSToolsConfig.model_validate(data)
  File "/Users/felipe.matos/Library/Application Support/cs_tools/.cs_tools/lib/python3.10/site-packages/pydantic/main.py", line 532, in model_validate
    return cls.__pydantic_validator__.validate_python(
  File "/Users/felipe.matos/Library/Application Support/cs_tools/.cs_tools/lib/python3.10/site-packages/pydantic_settings/main.py", line 84, in __init__
    super().__init__(
  File "/Users/felipe.matos/Library/Application Support/cs_tools/.cs_tools/lib/python3.10/site-packages/pydantic/main.py", line 175, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
  File "/Users/felipe.matos/Library/Application Support/cs_tools/.cs_tools/lib/python3.10/site-packages/pydantic_settings/main.py", line 84, in __init__
    super().__init__(
  File "/Users/felipe.matos/Library/Application Support/cs_tools/.cs_tools/lib/python3.10/site-packages/pydantic/main.py", line 175, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
  File "/Users/felipe.matos/Library/Application Support/cs_tools/.cs_tools/lib/python3.10/site-packages/cs_tools/settings.py", line 251, in encode_password
    utils.reveal(data.encode()).decode()
  File "/Users/felipe.matos/Library/Application Support/cs_tools/.cs_tools/lib/python3.10/site-packages/cs_tools/utils.py", line 71, in reveal
    return zlib.decompress(b64d(obscured))
zlib.error: Error -3 while decompressing data: incorrect header check
```

**Comment by boonhapus** [comment]
Hey @felipemm , I'm having a tough time tracking down what value would cause this error.

I was able to reproduce this by providing _only_ special characters as a password. Does that sound about like what you're doing?

**Comment by felipemm** [comment]
just tested with another user, no good. Maybe something related to python/lib version? Which version you're testing with?

**Comment by boonhapus** [comment]
I tried to recreate it with the same architecture you have @felipemm 

```
│ Python Version: Python 3.10.8 (main, Dec 8 2022, 10:52:18) [Clang 14.0.0 (clang-1400.0.29.202)] │
│ System Info: Darwin (detail: macOS-12.7.1-x86_64-i386-64bit) │
```

A username with an @ should be no problem, this is actually how my own config is set up.

It's possible that I've accidentally fixed this in 1.5.2 , which I should be releasing before Monday. 😅

**Comment by boonhapus** [comment]
@felipemm can you shoot me an email? Let's schedule some live time to look into this if you don't mind. 

nicholas.cooper@thoughtspot.com

**Comment by felipemm** [comment]
@boonhapus sure let's do it. FYI I thought this was something on my environment, I used another windows machine with python 3.10.4, same error

**Comment by felipemm** [comment]
odd. when limiting the size of password to 7 or less characters it works (it fails to connect, but do not generate exceptions)

**Comment by felipemm** [comment]
changed to 7 char the password and it worked. Weird

**Comment by boonhapus** [comment]
Thanks for investigating @felipemm !

😩 It's probably something with base64 encoding that I'm not understanding. I'm not sure why we're just now seeing this issue, but a couple customers reported it. It's been the same implementation for years now, hah.

Can you share some examples of the fake passwords values that worked or didn't work?

**Comment by boonhapus** [comment]
Actually, I think I'm able to pin this down. I have no idea _why_ it's suddenly causing us issues now..... but at least I know how to fix it.

**Comment by boonhapus** [comment]
@felipemm can you try bootstrapping again, and then try the password?

```
curl -sSL https://raw.githubusercontent.com/thoughtspot/cs_tools/master/cs_tools/updater/_bootstrapper.py | python3 - --install
```

**Comment by felipemm** [comment]
you nailed it! it is working now. What was the problem?

**Comment by boonhapus** [comment]
For some reason, we're just now reaching this error. I'm actually not sure exactly why though @felipemm , but I am catching the new zlib error and handling it appropriately.
