### ISSUE TITLE
Fail to execute any command of cs_tools on windows

### ISSUE THREAD

**Issue by senapathi-at-hyatt** [thoughtspot/cs_tools#165]
### First Stop

- [X] I have read and agreed to the ThoughtSpot Dev Tools EULA.
- [X] I understand that if I have a critical issue with ThoughtSpot, I should reach out to my designated Account Executive and Solutions Consultant team instead of cs_tools.
- [X] I searched the cs_tools documentation, with the integrated search.

### Platform Configuration

PS C:\Windows\system32> cs_tools self info --anonymous
cs_tools : Traceback (most recent call last):
At line:1 char:1
+ cs_tools self info --anonymous
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\2501104\AppData\Roaming\cs_tools\.cs_tools\Scripts\cs_tools.exe\__main__.py", line 4, in <module>
  File "C:\Users\2501104\AppData\Roaming\cs_tools\.cs_tools\Lib\site-packages\cs_tools\cli\commands\main.py", line 11, in <module>
    from cs_tools.cli import _analytics
  File "C:\Users\2501104\AppData\Roaming\cs_tools\.cs_tools\Lib\site-packages\cs_tools\cli\_analytics.py", line 26, in <module>
    from cs_tools.cli.ux import rich_console
  File "C:\Users\2501104\AppData\Roaming\cs_tools\.cs_tools\Lib\site-packages\cs_tools\cli\ux.py", line 12, in <module>
    from cs_tools.cli.types import SyncerProtocolType
  File "C:\Users\2501104\AppData\Roaming\cs_tools\.cs_tools\Lib\site-packages\cs_tools\cli\types.py", line 16, in <module>
    from cs_tools.cli.dependencies.syncer import DSyncer
  File "C:\Users\2501104\AppData\Roaming\cs_tools\.cs_tools\Lib\site-packages\cs_tools\cli\dependencies\__init__.py", line 1, in <module>
    from .thoughtspot import thoughtspot
  File "C:\Users\2501104\AppData\Roaming\cs_tools\.cs_tools\Lib\site-packages\cs_tools\cli\dependencies\thoughtspot.py", line 14, in <module>
    from cs_tools.settings import (
  File "C:\Users\2501104\AppData\Roaming\cs_tools\.cs_tools\Lib\site-packages\cs_tools\settings.py", line 225, in <module>
    _meta_config = MetaConfig.load()
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\2501104\AppData\Roaming\cs_tools\.cs_tools\Lib\site-packages\cs_tools\settings.py", line 116, in load
    instance = cls(**data, __is_old_format__=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\2501104\AppData\Roaming\cs_tools\.cs_tools\Lib\site-packages\pydantic\main.py", line 193, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for MetaConfig
remote.last_checked
  Value error, value should be a valid datetime representation, got None [type=value_error, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.8/v/value_error
analytics.last_checkpoint
  Value error, value should be a valid datetime representation, got None [type=value_error, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.8/v/value_error

### Description

Getting above attached error when a command of cs_tools is executed.

OS : Windows
Python version: 3.12

### Need to upload log files securely?

PS C:\Windows\system32> cs_tools logs report --latest 5
cs_tools : Traceback (most recent call last):
At line:1 char:1
+ cs_tools logs report --latest 5
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\2501104\AppData\Roaming\cs_tools\.cs_tools\Scripts\cs_tools.exe\__main__.py", line 4, in <module>
  File "C:\Users\2501104\AppData\Roaming\cs_tools\.cs_tools\Lib\site-packages\cs_tools\cli\commands\main.py", line 11, in <module>
    from cs_tools.cli import _analytics
  File "C:\Users\2501104\AppData\Roaming\cs_tools\.cs_tools\Lib\site-packages\cs_tools\cli\_analytics.py", line 26, in <module>
    from cs_tools.cli.ux import rich_console
  File "C:\Users\2501104\AppData\Roaming\cs_tools\.cs_tools\Lib\site-packages\cs_tools\cli\ux.py", line 12, in <module>
    from cs_tools.cli.types import SyncerProtocolType
  File "C:\Users\2501104\AppData\Roaming\cs_tools\.cs_tools\Lib\site-packages\cs_tools\cli\types.py", line 16, in <module>
    from cs_tools.cli.dependencies.syncer import DSyncer
  File "C:\Users\2501104\AppData\Roaming\cs_tools\.cs_tools\Lib\site-packages\cs_tools\cli\dependencies\__init__.py", line 1, in <module>
    from .thoughtspot import thoughtspot
  File "C:\Users\2501104\AppData\Roaming\cs_tools\.cs_tools\Lib\site-packages\cs_tools\cli\dependencies\thoughtspot.py", line 14, in <module>
    from cs_tools.settings import (
  File "C:\Users\2501104\AppData\Roaming\cs_tools\.cs_tools\Lib\site-packages\cs_tools\settings.py", line 225, in <module>
    _meta_config = MetaConfig.load()
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\2501104\AppData\Roaming\cs_tools\.cs_tools\Lib\site-packages\cs_tools\settings.py", line 116, in load
    instance = cls(**data, __is_old_format__=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\2501104\AppData\Roaming\cs_tools\.cs_tools\Lib\site-packages\pydantic\main.py", line 193, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for MetaConfig
remote.last_checked
  Value error, value should be a valid datetime representation, got None [type=value_error, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.8/v/value_error
analytics.last_checkpoint
  Value error, value should be a valid datetime representation, got None [type=value_error, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.8/v/value_error

**Comment by boonhapus** [comment]
Hey @senapathi-at-hyatt , I'm not quite sure how you got to this error, but can you navigate to this directory `C:\Users\2501104\AppData\Roaming\cs_tools` and delete the meta config json file?

**Comment by senapathi-at-hyatt** [comment]
Thanks @boonhapus, 
It is working after delete of "C:\Users\2501104\AppData\Roaming\cs_tools" folder and reinstall of cs_tools.

**Comment by senapathi-at-hyatt** [comment]
The issue is resolved.
